
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
 -  group: New variable group 22-Mar

stages:
  - stage: dev
    jobs:
      - job: python_install
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true
              architecture: 'x64'
          
          - script: |
              python -m pip install --upgrade pip
            displayName: Upgrade pip
            
          
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: '$(subscription)'
              KeyVaultName: 'devopskeyvault87'
              SecretsFilter: '*'
              RunAsPreJob: true

          - script: |
              if [ -n "$(my-secret1)" ]; then
                     echo "Key Vault integration works"
              else
                      echo "Key Vault integration failed"
                      exit 1
              fi
            displayName: Check secret
       
          

      

          